// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package model

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotifier creates a new instance of MockNotifier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotifier(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotifier {
	mock := &MockNotifier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotifier is an autogenerated mock type for the Notifier type
type MockNotifier struct {
	mock.Mock
}

type MockNotifier_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotifier) EXPECT() *MockNotifier_Expecter {
	return &MockNotifier_Expecter{mock: &_m.Mock}
}

// PostMessage provides a mock function for the type MockNotifier
func (_mock *MockNotifier) PostMessage(message string) error {
	ret := _mock.Called(message)

	if len(ret) == 0 {
		panic("no return value specified for PostMessage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(message)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotifier_PostMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PostMessage'
type MockNotifier_PostMessage_Call struct {
	*mock.Call
}

// PostMessage is a helper method to define mock.On call
//   - message string
func (_e *MockNotifier_Expecter) PostMessage(message interface{}) *MockNotifier_PostMessage_Call {
	return &MockNotifier_PostMessage_Call{Call: _e.mock.On("PostMessage", message)}
}

func (_c *MockNotifier_PostMessage_Call) Run(run func(message string)) *MockNotifier_PostMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockNotifier_PostMessage_Call) Return(err error) *MockNotifier_PostMessage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotifier_PostMessage_Call) RunAndReturn(run func(message string) error) *MockNotifier_PostMessage_Call {
	_c.Call.Return(run)
	return _c
}
