on:
  push:
    tags:
      - "v*"
jobs:
  release:
    uses: ./.github/workflows/reusable-release.yaml
    permissions:
      contents: write
    strategy:
      matrix:
        os:
          - ubuntu-latest
    with:
      os: "${{ matrix.os }}"