name: Pre-check
on:
  workflow_call:
    outputs:
      go:
        description: this is going to be true when go code is changed
        value: ${{ jobs.changed-files.outputs.go }}      
      workflow:
        description: this is going to be true when workflow files are changed
        value: ${{ jobs.changed-files.outputs.workflow }}
jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      go: ${{ steps.list-changed-files.outputs.go }}
      workflow: ${{ steps.list-changed-files.outputs.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get all changed files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47

      - name: List all changed files
        id: list-changed-files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          go=false
          workflow=false

          while IFS= read -r file; do
            if [[ "$file" == *.go ]]; then
              go=true
            fi

            if [[ "$file" == .github/workflows/* ]]; then
              workflow=true
            fi
          done <<< "$ALL_CHANGED_FILES"

          echo "go=$go" >> "$GITHUB_OUTPUT"
          echo "workflow=$workflow" >> "$GITHUB_OUTPUT"
  