name: Pre-check
on:
  workflow_call:
    outputs:
      go:
        description: this is going to be true when go code is changed
        value: ${{ jobs.changed-files.go }}      
      workflow:
        description: this is going to be true when workflow files are changed
        value: ${{ jobs.changed-files.workflow }}
jobs:
  changed-files:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    outputs:
      go: ${{ steps.list-changed.go }}
      workflow: ${{ steps.list-changed.workflow }}
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Get all changed markdown files
        id: changed-files
        uses: tj-actions/changed-files@24d32ffd492484c1d75e0c0b894501ddb9d30d62 # v47

      - name: List all changed files
        id: list-changed-files
        env:
          ALL_CHANGED_FILES: ${{ steps.changed-files.outputs.all_changed_files }}
        run: |
          go=false
          workflow=false

          for file in ${ALL_CHANGED_FILES}; do
            echo "$file was changed"

            if [[ "$file" == *.go ]]; then
              go=true
            fi

            if [[ "$file" == .github/workflows/* ]]; then
              workflow=true
            fi
          done

          if $go_changed; then
            echo "go=true" >> $GITHUB_OUTPUT
          fi

          if $workflow_changed; then
            echo "workflow=true" >> $GITHUB_OUTPUT
          fi
  