on:
  pull_request:
    branches:
      - main
jobs:
  test:
    uses: ./.github/workflows/reusable-actions/test.yaml
    permissions:
      contents: read
      actions: read
      pull-requests: write
    strategy:
      matrix:
        test:
          - os: macos-13
          - os: macos-latest
            report-coverage: true
      fail-fast: false
    name: MacOS test (${{ matrix.test.os }})
    with:
      os: "${{ matrix.test.os }}"
      report-coverage: ${{ matrix.test.report-coverage || false }}
      pull-request-number: "${{ github.event.pull_request.number }}"
  lint:
    name: Lint Go code
    runs-on: macos-latest
    permissions:
      contents: read
      actions: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@08eba0b27e820071cde6df949e0beb9ba4906955 # v4.3.0
        with:
          persist-credentials: false

      - name: Setup go
        uses: actions/setup-go@d35c59abb061a4a6fb18e82ac0862c26744d6ab5 # v5.5.0
        with:
          go-version-file: "./go.mod"
          cache-dependency-path: "./go.sum"
      
      - name: Lint
        uses: reviewdog/action-golangci-lint@f9bba13753278f6a73b27a56a3ffb1bfda90ed71 # v2.8.0
        with:
          go_version_file: "./go.mod"
          reporter: github-pr-review
          fail_level: error

